export const START = "START";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const FAILED = "FAILED";
export const GET_ALL_STORE_SUCCESS = "GET_ALL_STORE_SUCCESS";
export const GET_STORE_PRODUCTS_SUCCESS = "GET_STORE_PRODUCTS_SUCCESS";